edition = "2021"
unstable_features = true

remove_nested_parens = true
combine_control_expr = true
condense_wildcard_suffixes = true
disable_all_formatting = false
fn_single_line = true
empty_item_single_line = true
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = false
format_macro_matchers = true
format_macro_bodies = true
format_strings = false
hard_tabs = true
match_arm_blocks = true
match_block_trailing_comma = true
merge_derives = true
normalize_comments = true
normalize_doc_attributes = false
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_lit_single_line = false

max_width = 100
array_width = 60
chain_width = 60
fn_call_width = 60
comment_width = 100
attr_fn_like_width = 60
inline_attribute_width = 0
blank_lines_lower_bound = 1
blank_lines_upper_bound = 1
enum_discrim_align_threshold = 0
struct_field_align_threshold = 0
doc_comment_code_block_width = 100

binop_separator = "Front"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysSameLine"
imports_indent = "Block"
imports_layout = "Vertical"
indent_style = "Block"
match_arm_leading_pipes = "Never"
imports_granularity = "Crate"
newline_style = "Unix"
group_imports = "StdExternalCrate"
trailing_comma = "Always"
